# Generated by Django 3.1.7 on 2021-03-21 12:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='用户名')),
                ('signature', models.CharField(max_length=50, verbose_name='个性签名')),
                ('email', models.CharField(max_length=100, verbose_name='邮箱')),
                ('password', models.CharField(max_length=100, verbose_name='密码字段')),
                ('status', models.CharField(max_length=10, verbose_name='状态')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('body', models.TextField(verbose_name='正文')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('author_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='blog.user', verbose_name='文章作者ID')),
            ],
        ),
    ]
