# Generated by Django 3.1.7 on 2021-03-21 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('A', '正常'), ('B', '封禁中'), ('C', '已注销')], max_length=1, verbose_name='状态'),
        ),
    ]
