# Generated by Django 3.1.7 on 2021-03-22 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_fuck'),
    ]

    operations = [
        migrations.DeleteModel(
            name='fuck',
        ),
    ]
