# Generated by Django 3.1.7 on 2021-03-22 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_delete_fuck'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='signature',
            field=models.CharField(default=' ', max_length=50, verbose_name='个性签名'),
        ),
    ]
