# Generated by Django 3.1.7 on 2021-03-23 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20210322_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='signature',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='个性签名'),
        ),
    ]
