# Generated by Django 3.1.7 on 2021-03-28 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20210327_2237'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='codehilite_style',
            field=models.CharField(default='vim', max_length=25, verbose_name='代码高亮主题'),
        ),
    ]
