# Generated by Django 3.1.7 on 2021-04-01 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20210331_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='censored',
            field=models.BooleanField(default=False, verbose_name='已审核'),
        ),
        migrations.AddField(
            model_name='article',
            name='visible',
            field=models.BooleanField(default=False, verbose_name='可见'),
        ),
    ]
