# Generated by Django 3.1.7 on 2021-04-02 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20210401_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='censored',
            field=models.BooleanField(default=True, verbose_name='已审核'),
        ),
        migrations.AlterField(
            model_name='article',
            name='visible',
            field=models.BooleanField(default=True, verbose_name='可见'),
        ),
    ]
